### ISSUE TITLE
generating Plugin Doesn`t return $result by default.

### ISSUE THREAD

**Issue by thokiller** [Mage2Gen/Mage2Gen#242]
Magento 2.2.6 broke after installing a generated module. I found out that the cause of this was a plugin that returned nothing. (See screenshot)
![screenshot from 2018-12-06 10-18-37](https://user-images.githubusercontent.com/35527212/49574287-59865880-f940-11e8-85bc-bef276de5504.png)

**Comment by tuyennn** [comment]
@thokiller This depends on your code and your method with parameters you want to implement, how the Generator knows which things you defined inside your plugin method?

**Comment by lewisvoncken** [comment]
@tuyennn We are working on this! Maybe before the end of the year!
