### ISSUE TITLE
Block Class Not generated

### ISSUE THREAD

**Issue by hassanas** [Mage2Gen/Mage2Gen#282]
I try to create block class in my custom module but its not visible in preview:-
![Screenshot from 2019-05-10 04-52-55](https://user-images.githubusercontent.com/4970893/57493806-f4180880-72df-11e9-89ef-43d4470a36d1.png)
Also code generated directories for this block are not correct, It create block directory outside of the module

**Comment by krukas** [comment]
@hassanas It looks like you also specified the whole path for the classname. This is not necessary only the classname from the block perspective. 

But it looks like there is a bug when the first classname has the same name as the vendor or first two parts are the same as vendor and module.
