### ISSUE TITLE
Category Yes/No attributes not working show as text box

### ISSUE THREAD

**Issue by zaheerbadi** [Mage2Gen/Mage2Gen#327]
When we try to create category attribute with Yes/No attribute type it show textbox in the backend form.
For Magento2.3

![image](https://user-images.githubusercontent.com/9264676/72046289-16827b80-32de-11ea-980d-6e428b9e54da.png)

I have replaced UI form code with this and working fine.
`<field name="display_on_homepage" sortOrder="100" formElement="checkbox">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="source" xsi:type="string">category</item>
                    <item name="default" xsi:type="number">0</item>
                </item>
            </argument>
            <settings>
                <validation>
                    <rule name="required-entry" xsi:type="boolean">false</rule>
                </validation>
                <dataType>boolean</dataType>
                <label translate="true">Display On Homepage</label>
            </settings>
            <formElements>
                <checkbox>
                    <settings>
                        <valueMap>
                            <map name="false" xsi:type="string">0</map>
                            <map name="true" xsi:type="string">1</map>
                        </valueMap>
                        <prefer>toggle</prefer>
                    </settings>
                </checkbox>
            </formElements>
        </field>`

**Comment by lewisvoncken** [comment]
@zaheerbadi 
this has been resolved in the latest release
