### ISSUE TITLE
Admin Grid (component UI)  - pagination breaks when going back

### ISSUE THREAD

**Issue by Volvoxpl** [Mage2Gen/Mage2Gen#354]
On Admin Grid, when you click on next page (eg. going from page 2 to 3) everything works OK, but when you click button to switch to previous page (eg. back to page 2 from 3) it does not display grid correctly (all items are this same item from last page).

This is because generated XML for `Vendor\Name\view\adminhtml\ui_component\vendor_name_model_listing.xml` in section `<dataSource component="Magento_Ui/js/grid/provider" name="vendor_name_model_listing_data_source">` in `<settings>` doesn't have:
```
<storageConfig>
    <param name="indexField" xsi:type="string">model_id</param>
</storageConfig>
```

**Comment by lewisvoncken** [comment]
@Volvoxpl 
This is resolved thanks to @tdgroot in the latest release
https://github.com/Mage2Gen/Mage2Gen/pull/356
