### ISSUE TITLE
Creating Customer attribute

### ISSUE THREAD

**Issue by ejaz-alam** [Mage2Gen/Mage2Gen#365]
When we create customer attributes. It assigns the input type as varchar which is not valid and it gives an error when we open it in customer form.

**error:**
TypeError: Argument 1 passed to Magento\Ui\Component\Form\Element\AbstractOptionsField::convertOptionsValueToString() must be of the type array, null given, called in /var/www/html/vendor/magento/module-......

![image](https://user-images.githubusercontent.com/22393364/109606995-4d9e9680-7b49-11eb-8d52-8cb6a9613e03.png)

**Comment by lewisvoncken** [comment]
@ejaz-alam this has been resolved in the latest release
