### ISSUE TITLE
Custom Customer Billing Address Paypal Issue

### ISSUE THREAD

**Issue by shinesoftware** [Mage2Gen/Mage2Gen#374]
Hi guys,

first of all thanks for your helpful tool! We have found a weird behavior when we create a simple module with one custom customer field into the billing address. 

When a customer tries to checkout his cart paying by the paypal gateway, **no data are saved into the quote_address database table**.

![image](https://user-images.githubusercontent.com/1553035/112652427-b4178b80-8e4d-11eb-9dbd-f5570acc4f41.png)

We have prepared this module for you: https://mage2gen.com/load/dad3f7b7-a83a-4f85-aa6f-9a57f17848dc?main_version=3

Regards

**Comment by lewisvoncken** [comment]
Hi @shinesoftware 

You should add `experius/module-extracheckoutaddressfields` to your composer require

Which is referred to in the tooltip
![image](https://user-images.githubusercontent.com/6040343/112820840-5326c800-9086-11eb-9d46-dacb6f24702b.png)

**Comment by shinesoftware** [comment]
Hello @lewisvoncken we have installed that module and tested but we have noticed that the problem is still there: https://github.com/experius/Magento-2-Module-Experius-ExtraCheckoutAddressFields/issues/17 maybe the @MaikelExperius could help us! thanks guys

**Comment by lewisvoncken** [comment]
@shinesoftware 
I will try to take a look at your issue this week

**Comment by shinesoftware** [comment]
@lewisvoncken thanks! I am really curious to know what does not work! I have spent a week to debug it!

**Comment by shinesoftware** [comment]
hi guys,

any news about this issue?

thanks

**Comment by shinesoftware** [comment]
Up

**Comment by shinesoftware** [comment]
@lewisvoncken any news?

**Comment by shinesoftware** [comment]
hi guys, any news?
