### ISSUE TITLE
Error on order_address table

### ISSUE THREAD

**Issue by manuelcanepa-lyracons** [Mage2Gen/Mage2Gen#375]
https://github.com/Mage2Gen/Mage2Gen/blob/f9fcc5e48526d7570433dbe153a380e707198113/mage2gen/snippets/customerattribute.py#L341

This code will create a new table called `order_address` instead of use the real `sales_order_address`

**Comment by borisvankatwijk** [comment]
@manuelcanepa-lyracons , Thank you for the submission.

This has resolved for magento-2.3 and magento-2.4 (main branches of these).

A release to mage2gen.com will follow shortly.
