### ISSUE TITLE
Source model incorrect when creating boolean product attribute

### ISSUE THREAD

**Issue by experius-nl** [Mage2Gen/Mage2Gen#377]
\Boekenwereld\BookDirectAvailability\Magento\Eav\Model\Entity\Attribute\Source\Boolean\DirectlyAvailable::class should have been Magento\Eav\Model\Entity\Attribute\Source\Boolean

**Comment by borisvankatwijk** [comment]
@lewisvoncken ,

Cherry-pick for magento-2.4 is done/released.
