### ISSUE TITLE
Customer(Section) Data - missing semicolon in generated function getSectionData()

### ISSUE THREAD

**Issue by 4ctobias** [Mage2Gen/Mage2Gen#384]
Hi,

when I add an Customer(Section) data, the function getSectionData() generated is incorrect - the semicolon is missing in the return-statement:

```
/**
 * {@inheritdoc}
 */
public function getSectionData()
{
    return []
}
```

Best,
Tobias

**Comment by borisvankatwijk** [comment]
@4ctobias , thank you for the submission.
This has resolved for magento-2.3 and magento-2.4 (main branches of these).
A release to mage2gen.com will follow shortly.
