### ISSUE TITLE
Set identify field default to unsigned int with 10 padding

### ISSUE THREAD

**Issue by evs-xsarus** [Mage2Gen/Mage2Gen#391]
Currently, when adding a new field for a model with a table, the selectbox 'identity' adds an primary field. This field is set to be a smallint with padding 6. 

I've had many times where de max value was reached and got duplicate value errors.

I suggest setting the type and padding by default to an unsigned int, padding 10.

![image](https://user-images.githubusercontent.com/44158071/147640382-b7ed254f-ac7b-4f9e-8b4f-ddc153e35be3.png)

Related: https://github.com/Mage2Gen/Mage2Gen/issues/287

**Comment by borisvankatwijk** [comment]
Hi @evs-xsarus ,

Thank you for the submission!

This has been [changed to int](https://github.com/Mage2Gen/Mage2Gen/commit/2f53313f0f69419ed1314a7ca57781485a51a70f) and [padding 10](https://github.com/Mage2Gen/Mage2Gen/commit/aed109d4c7665f974438434ca8235a678c1a7728) a release just now.

I hope that resolves the issue's.
