### ISSUE TITLE
Model field sorting feature

### ISSUE THREAD

**Issue by shinesoftware** [Mage2Gen/Mage2Gen#51]
When I try to create a module sometimes I am focusing on the structure of the model (database) and I forget about the sorting of the fields. One of the best feature is the sorting of the fields in the model section in order to create a perfect form in Magento administration panel.

thanks

**Comment by krukas** [comment]
Do you mean you can set the sort order per field to change the order in Grid and Form?

**Comment by shinesoftware** [comment]
yes, I mean a way to move up or down the field sorting. A textbox that helps the user to sort them is a good start.
