### ISSUE TITLE
Extension attributes plugins

### ISSUE THREAD

**Issue by twosg** [Mage2Gen/Mage2Gen#54]
I am just wondering, when adding a new customer attribute, don't we need to implement plugins for loading and saving the extension attribute? It seems that is missing in the generator.

**Comment by krukas** [comment]
We are looking into it to make this possible. I think extension attributes needs to be an snippet option, because not everyone wants to have a plugin on save for a simple attribute.

**Comment by twosg** [comment]
How would the new attribute be saved without plugin then? When I just add the attribute eg. to the adminhtml customer address form, and if I set a value and save, the field is blank after save.

**Comment by robbertstevens** [comment]
@twosg Extension attributes are a pain, I dont get them working either even with a plugin.
