### ISSUE TITLE
How to create a TextArea & File attachment?

### ISSUE THREAD

**Issue by shinesoftware** [Mage2Gen/Mage2Gen#88]
Hello,

as described in the subject: How have I to create a textarea in the form?

Is there a way to create a file attachment object?

thanks

**Comment by shinesoftware** [comment]
why it has been closed?

**Comment by krukas** [comment]
Hi @shinesoftware,

This can be an advanced option because for admin panel its ui components. File attachments (http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-fileuploader.html).

Sorry close was a mis click

**Comment by shinesoftware** [comment]
I cannot see in the Model panel the Varchar option type... is it correct?

![schermata 2017-07-17 alle 15 27 36](https://user-images.githubusercontent.com/1553035/28270174-d3cbcb5a-6b04-11e7-9b26-6b9686f947f5.png)

**Comment by krukas** [comment]
@shinesoftware Yes this is correct, the model snippet show all the DB fields and Magento 2 only has text and no varchar.

**Comment by shinesoftware** [comment]
In concern the textarea the problem is not the database field type but the way to show the html element in the form that the mage2gen has been generated. there is not any way to set an html object into textarea with your software.

**Comment by krukas** [comment]
We could create an extra option for that when field type text is selected.
